#pragma once
#include <array>
#include <vector>
#include <string>
#include <memory>
#include <mutex>
#include <iostream>
#include <functional>
#include <sstream>
#include <csignal>
#include <limits>
#include <cstring>
#include <algorithm>
#include <deque>
#include <cstddef>
#include <queue>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <map>
#include <stack>
#include <cassert>
#include <cmath>
#include <random>
#include <filesystem>
//#include <format> //C++20